// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_qxB--IYaSo2TANXeX0XIMC2N0z8h9mU',
    appId: '1:975640941576:web:f964eda7690f98db966dbd',
    messagingSenderId: '975640941576',
    projectId: 'projetopi5',
    authDomain: 'projetopi5.firebaseapp.com',
    storageBucket: 'projetopi5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw1eRbEc31n-zw-GwdJfZ9yZ6xs7ynpUs',
    appId: '1:975640941576:android:35eab8244e029c54966dbd',
    messagingSenderId: '975640941576',
    projectId: 'projetopi5',
    storageBucket: 'projetopi5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYUZOerOsyYjVi0v3WgMxtoP-JMZ0vms',
    appId: '1:975640941576:ios:fe062f48a2a64de3966dbd',
    messagingSenderId: '975640941576',
    projectId: 'projetopi5',
    storageBucket: 'projetopi5.appspot.com',
    iosClientId: '975640941576-anc4j0lp2vl5nqb6hvoipfq5ct825mjt.apps.googleusercontent.com',
    iosBundleId: 'br.gov.sp.cps.fatecitapira.mediaSuggester',
  );

}